---

# Configure pacman & install yay
- name: Check if China mirrors ars used
  ansible.builtin.lineinfile:
    path: /etc/pacman.d/mirrorlist
    line: "## Manjaro Linux custom mirrorlist"
    state: present
  check_mode: true
  register: check_mirrors
- name: Use China mirrors if not using
  ansible.builtin.shell:
    cmd: pacman-mirrors -c China -m rank
  become: true
  when: check_mirrors.changed
  register: China_mirrors
- name: Add archlinuxcn to pacman.conf
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [archlinuxcn]
      SigLevel = Optional TrustedOnly
      Server = https://repo.huaweicloud.com/archlinuxcn/$arch
  become: true
  register: archlinuxcn
- name: Refresh package lists
  ansible.builtin.pacman:
    update_cache: true
  become: true
  when: China_mirrors.changed or archlinuxcn.changed
- name: Install archlinuxcn-keyring, yay
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - archlinuxcn-keyring
    - yay
  become: true